services:
  mysql:
    image: mysql:latest
    container_name: some-mysql
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
    - "8080:80"
    restart: always
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql